# hello-go-deploy-ecs task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: hello-go-deploy-ecs

outputs:
- name: coverage-results

run:
  path: ./hello-go-deploy-ecs/ci/scripts/unit-tests.sh
  # args: [-debug]
  