# hello-go-deploy-amazon-ecs task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: hello-go-deploy-amazon-ecs

outputs:
- name: hello-go-deploy-amazon-ecs-updated

run:
  path: ./hello-go-deploy-amazon-ecs/ci/scripts/readme-github-pages.sh
  # args: [-debug]

