# hello-go-deploy-ecs task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: hello-go-deploy-ecs

run:
  path: ./hello-go-deploy-ecs/ci/scripts/deploy.sh
  # args: [-debug]

